# PyTorch Tutorial Notebook

This notebook follows the official PyTorch tutorials and is organized into four parts:

1. **Tensors**  
    In this tutorial, you will learn the basics of PyTorch tensors.  
    `blitz/tensor_tutorial.html`

2. **A Gentle Introduction to `torch.autograd`**  
    Learn about autograd.  
    `blitz/autograd_tutorial.html`

3. **Neural Networks**  
    This tutorial demonstrates how you can train neural networks in PyTorch.  
    `blitz/neural_networks_tutorial.html`

4. **Training a Classifier**  
    Learn how to train an image classifier in PyTorch by using the CIFAR10 dataset.  
    `blitz/cifar10_tutorial.html`

The goal of this notebook is to provide a hands-on introduction to the core PyTorch workflow, from tensor operations to training a simple classifier.

In [2]:
import torch
import numpy as np

data = [[1, 2],
        [3, 4]]
x_data = torch.tensor(data=data)
print(f"From data: {x_data}")

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"From numpy array: {x_np}")

#tensor of 1s like from another tensor(retaining the properties)
x_ones = torch.ones_like(x_data) #retain the properties of x_data (shape, datatype)
print(x_ones)
#tensor of random from another tensor, overriding properties
x_rand = torch.rand_like(x_data, dtype=torch.float) #overrides the properties of x_data
print(x_rand)

From data: tensor([[1, 2],
        [3, 4]])
From numpy array: tensor([[1, 2],
        [3, 4]])
tensor([[1, 1],
        [1, 1]])
tensor([[0.1926, 0.1911],
        [0.4224, 0.6352]])


In [ ]:
shape = (2, 3,) #Tuple of tensor dimensions (2 rows, 3 columns)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.4435, 0.2054, 0.2378],
        [0.5513, 0.9440, 0.3373]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [6]:
#Moving tensor to the GPU if available
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else 'cpu'
tensor = tensor.to(device=device)
print(f"Tensor is stored on: {tensor.device}")

Tensor is stored on: cuda:0


In [15]:
tensor = torch.ones(4, 4,)
tensor[:,1] = 0 #butun satirlari, ikinci sutundaki 0 yap
print(tensor)
print()

#element wise multiplication:
tensor_2 = tensor
tensor_2[:,2] = 0
tensor = tensor.mul(tensor_2)
tensor = tensor * tensor_2
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.]])


In [19]:
t = torch.ones(5)
print(f"t={t}")
n = t.numpy()
print(f"n={n}")

t.add_(5)
print(f"t={t}")
print(f"n={n}")

t=tensor([1., 1., 1., 1., 1.])
n=[1. 1. 1. 1. 1.]
t=tensor([6., 6., 6., 6., 6.])
n=[6. 6. 6. 6. 6.]


In [ ]:
n = np.ones(5)
print(f"n={n}")
t = torch.from_numpy(n)
print(f"t={t}")

np.add(n, 1, out=n)
print(f"n={n}")
print(f"t={t}")

n=tensor([6., 6., 6., 6., 6.])
n=tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
